name: Go

on:
  pull_request: {}
  push:
    branches:
      - main

    tags:
      - "*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "^1.19"

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6.4.1

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest

    if: >
      startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "^1.19"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
